---
# tasks file for common




- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day


- name: Install ansible on the automation(ansible-server)
    
  become: true
  apt:
    name: ansible
  
#ref https://www.middlewareinventory.com/blog/ansible-update-etc-hosts-file-across-all-hosts/
- name: Add controller and worker names to the /etc/hosts file 
  become: true
  lineinfile:
    path: "/etc/hosts" 
    line: "{{hostvars[item]['ansible_host']}} {{item}}"
    state: present
    backup: yes
  with_items: 
    - "{{ groups['kube-worker-private']}}"
    - "{{ groups['kube-controller-private'] }}"