- name: Create a deployment for the nginx web server
  shell: "kubectl create deployment nginx --image=nginx"

- name: List the pod created by the nginx deployment
  shell: "kubectl get pods -l app=nginx -o jsonpath=\"{.items[0].metadata.name}\""
  register: POD_NAME
  failed_when: "POD_NAME.stdout | length <= 0" # returns empty if not found


- debug:  msg="{{POD_NAME.stdout_lines}}"

- name: Port Forwarding| Forward port 8080 on your local machine to port 80 of the nginx pod
  shell: "kubectl port-forward {{POD_NAME.stdout}} 8080:80"
  register: command_output

- debug: msg="{{command_output.stdout_lines}}"


- name: Make an HTTP request using the forwarding address
  shell: "curl --head http://127.0.0.1:8080"
  register: command_output

- debug: msg="{{command_output.stdout_lines}}"


