---

########################---Exec---###############################

- name: Verify the ability to execute commands in a container


  shell: "kubectl exec -ti {{POD_NAME.stdout}} -- nginx -v"
  register: command_output
  failed_when: "'nginx version:' not in command_output.stdout" 
